### ISSUE TITLE
VFG visualization example

### ISSUE THREAD

**Issue by tyb0807** [axt/bingraphvis#4]
Hello,

I am currently exploring angr's VFG analysis, but I cannot visualize the VFG, by following the CFG example and changing **cfg.graph** to **vfg.graph**... It would be nice if you can show me the way to generate graphically the VFG. 

Thanks a lot

**Comment by axt** [comment]
Hi!

Because of https://github.com/angr/angr/issues/205, VFG graph edges are not generated correctly by https://github.com/angr/angr. This means the graph only has nodes, but no edges, thats why I didn't included any VFG visualization codes into https://github.com/axt/angr-utils.

You can always use the default visualization:
```python
import networkx 
networkx.write_dot(vfg.graph, 'vfg.dot');
```

Or you can use `plot_common` function in https://github.com/axt/angr-utils, for any generic graph visualization for which there is no domain-specific support:
```
from angrutils import plot_common
plot_common(vfg.graph, 'vfg.dot', format='raw')
```

The same at low-level in bingraphvis:

```python
from bingraphvis import *
from bingraphvis.angr import *
from bingraphvis.angr.x86 import *

vis = Vis()
vis.set_source(AngrCommonSource())
vis.add_content(AngrCommonHead())
vis.add_content(AngrCommonTypeHead())
vis.set_output(DotOutput('vfg.dot', format='raw'))
vis.process(vfg.graph)
```

You can create your own `AngrVFG*` components, and use them instead of `AngrCommon*`, if you want to have a more specific support for VFGs.

**Comment by tyb0807** [comment]
Thank you for your reply.

I have seen angr/angr#205 before but I thought they fixed it. 

And because of your screenshot from angr/angr#223 that I thought I could visualize VFG with **bingraphvis**. Btw, did you create your own `AngrVFG` for your screenshots?

Again, thanks a lot for your help.

**Comment by axt** [comment]
The screenshot is a simple CFG with debugging info enabled. 
(see here:. https://github.com/axt/angr-utils/blob/master/angrutils/visualize.py#L14 ). 

I just spent a small amount of time with VFG, because without the edges it doesn't make too much sense to visualize it (see the pic below):

![cica](https://cloud.githubusercontent.com/assets/759365/20633563/57d3d336-b348-11e6-99df-13526b089028.png)

Basically that is why there is currently no explicit support for it. If the edges will be fixed, I plan to add support for them.

Creating 'AngrVFGHead', 'AngrVFGContent', etc classes is not so hard. The goal of bingraphvis is that you can create a 'visualization pipeline' from simple pieces, like:
 - pretty-print node info: 
https://github.com/axt/bingraphvis/blob/master/bingraphvis/angr/content.py#L10
 - display some content related to the node: https://github.com/axt/bingraphvis/blob/master/bingraphvis/angr/content.py#L157
 - transform the graph somehow: https://github.com/axt/bingraphvis/blob/master/bingraphvis/angr/transform.py#L79
 - add visual annotation to nodes and edges: https://github.com/axt/bingraphvis/blob/master/bingraphvis/angr/annotator.py#L7
 - add extra annotations to the content https://github.com/axt/bingraphvis/blob/master/bingraphvis/angr/x86/annotator.py#L80
